In [9]:
#import data

import pandas as pd

df = pd.read_csv('West_Africa_temperature_1980_2022.csv')

In [11]:
df

,STATION,LATITUDE,LONGITUDE,ELEVATION,COUNTRY,1980-01-01 00:00:00,1980-01-02 00:00:00,1980-01-03 00:00:00,1980-01-04 00:00:00,1980-01-05 00:00:00,...,2022-12-22 00:00:00,2022-12-23 00:00:00,2022-12-24 00:00:00,2022-12-25 00:00:00,2022-12-26 00:00:00,2022-12-27 00:00:00,2022-12-28 00:00:00,2022-12-29 00:00:00,2022-12-30 00:00:00,2022-12-31 00:00:00
0,UV000005502,13.580,-2.430,340.0,Burkina Faso,23.89,24.44,24.44,23.33,23.89,...,24.44,23.33,23.33,23.33,22.78,25.00,25.56,25.00,25.00,24.44
1,UV000005507,12.070,0.350,301.0,Burkina Faso,24.44,24.44,25.00,25.00,25.56,...,23.33,23.33,22.78,22.78,22.78,24.44,25.00,24.44,24.44,23.33
2,UV000005522,10.330,-3.180,333.0,Burkina Faso,26.67,27.22,26.11,26.11,27.22,...,25.00,25.00,23.89,23.33,22.78,24.44,25.56,25.56,25.56,25.00
3,UV000065501,14.033,-0.033,277.0,Burkina Faso,21.67,24.44,22.78,23.33,23.89,...,32.22,32.22,32.22,32.22,32.22,32.22,32.22,32.22,32.22,32.22
4,UV000065516,11.750,-2.933,271.0,Burkina Faso,24.44,26.11,25.00,24.44,25.56,...,23.89,23.89,22.78,22.78,22.22,24.44,25.00,25.00,23.89,23.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,SL000061856,8.617,-13.200,27.0,Sierra Leone,26.67,26.67,26.67,26.67,26.67,...,27.78,28.33,26.67,27.78,28.33,26.67,26.67,27.22,26.67,27.22
68,LIM00065660,6.234,-10.362,9.4,Liberia,27.78,27.78,27.78,27.78,27.78,...,26.67,26.11,25.56,27.22,28.33,26.67,29.44,27.22,28.89,28.89
69,GHM00065472,5.605,-0.167,62.5,Ghana,26.11,28.89,28.89,28.89,28.89,...,28.33,28.33,27.78,28.33,27.22,27.78,28.89,28.33,28.89,27.78
70,CVM00008594,16.741,-22.949,53.9,Cape Verde,21.67,22.22,21.11,21.67,21.67,...,23.33,23.89,23.33,22.78,22.22,21.67,22.22,22.22,22.22,22.22
71,GV000001832,9.570,-13.620,46.0,Guinea,26.11,26.11,26.11,26.11,26.11,...,28.33,27.22,27.22,27.22,28.33,28.33,28.33,27.22,28.33,28.33

In [3]:
df = df.T

In [4]:
df

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
STATION,UV000005502,UV000005507,UV000005522,UV000065501,UV000065516,UVM00065503,UVM00065510,UVM00065518,IV000005557,IV000005562,...,SGM00061679,SGM00061695,SGM00061697,SGM00061698,SGM00061699,SL000061856,LIM00065660,GHM00065472,CVM00008594,GV000001832
LATITUDE,13.58,12.07,10.33,14.033,11.75,12.353,11.16,11.15,6.13,6.65,...,14.147,12.556,12.41,12.883,12.572,8.617,6.234,5.605,16.741,9.57
LONGITUDE,-2.43,0.35,-3.18,-0.033,-2.933,-1.512,-4.331,-1.15,-5.95,-4.7,...,-16.051,-16.282,-16.746,-14.967,-12.22,-13.2,-10.362,-0.167,-22.949,-13.62
ELEVATION,340.0,301.0,333.0,277.0,271.0,316.1,460.6,322.0,205.0,110.0,...,7.9,22.9,15.8,10.0,178.0,27.0,9.4,62.5,53.9,46.0
COUNTRY,Burkina Faso,Burkina Faso,Burkina Faso,Burkina Faso,Burkina Faso,Burkina Faso,Burkina Faso,Burkina Faso,Ivory Coast,Ivory Coast,...,Senegal,Senegal,Senegal,Senegal,Senegal,Sierra Leone,Liberia,Ghana,Cape Verde,Guinea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27 00:00:00,25.0,24.44,24.44,32.22,24.44,24.44,25.56,23.89,25.0,25.56,...,26.11,23.33,22.78,25.56,28.33,26.67,26.67,27.78,21.67,28.33
2022-12-28 00:00:00,25.56,25.0,25.56,32.22,25.0,25.0,26.11,25.56,27.22,27.78,...,23.89,22.78,22.78,23.89,28.33,26.67,29.44,28.89,22.22,28.33
2022-12-29 00:00:00,25.0,24.44,25.56,32.22,25.0,25.56,26.11,25.56,26.67,27.22,...,24.44,23.33,22.78,24.44,23.89,27.22,27.22,28.33,22.22,27.22
2022-12-30 00:00:00,25.0,24.44,25.56,32.22,23.89,24.44,25.56,25.56,25.56,26.11,...,26.11,22.78,23.33,22.22,24.44,26.67,28.89,28.89,22.22,28.33
2022-12-31 00:00:00,24.44,23.33,25.0,32.22,23.33,24.44,24.44,24.44,26.67,24.44,...,26.67,24.44,24.44,25.56,27.22,27.22,28.89,27.78,22.22,28.33

In [5]:
# Set the second row as the header
new_header = df.iloc[0]  # Grab the first row for the header

df = df[1:]  # Take the data less the header row

df.columns = new_header  #Set the header row as the df header

In [6]:
df_main = df[4:]

In [7]:
df_main.head()

STATION,UV000005502,UV000005507,UV000005522,UV000065501,UV000065516,UVM00065503,UVM00065510,UVM00065518,IV000005557,IV000005562,...,SGM00061679,SGM00061695,SGM00061697,SGM00061698,SGM00061699,SL000061856,LIM00065660,GHM00065472,CVM00008594,GV000001832
1980-01-01 00:00:00,23.89,24.44,26.67,21.67,24.44,23.33,24.44,26.67,25.56,24.44,...,26.67,23.33,26.67,28.89,30.0,26.67,27.78,26.11,21.67,26.11
1980-01-02 00:00:00,24.44,24.44,27.22,24.44,26.11,25.0,26.11,26.67,25.56,27.22,...,26.67,24.44,26.67,27.78,26.11,26.67,27.78,28.89,22.22,26.11
1980-01-03 00:00:00,24.44,25.0,26.11,22.78,25.0,25.56,25.0,26.67,26.11,27.22,...,26.67,23.33,26.67,28.89,27.78,26.67,27.78,28.89,21.11,26.11
1980-01-04 00:00:00,23.33,25.0,26.11,23.33,24.44,24.44,25.0,26.67,26.67,26.67,...,26.67,21.67,26.67,23.33,28.33,26.67,27.78,28.89,21.67,26.11
1980-01-05 00:00:00,23.89,25.56,27.22,23.89,25.56,25.56,26.67,26.67,26.11,26.67,...,24.44,24.44,26.67,23.33,27.22,26.67,27.78,28.89,21.67,26.11

In [12]:
df_main.tail()

STATION,UV000005502,UV000005507,UV000005522,UV000065501,UV000065516,UVM00065503,UVM00065510,UVM00065518,IV000005557,IV000005562,...,SGM00061679,SGM00061695,SGM00061697,SGM00061698,SGM00061699,SL000061856,LIM00065660,GHM00065472,CVM00008594,GV000001832
2022-12-27 00:00:00,25.0,24.44,24.44,32.22,24.44,24.44,25.56,23.89,25.0,25.56,...,26.11,23.33,22.78,25.56,28.33,26.67,26.67,27.78,21.67,28.33
2022-12-28 00:00:00,25.56,25.0,25.56,32.22,25.0,25.0,26.11,25.56,27.22,27.78,...,23.89,22.78,22.78,23.89,28.33,26.67,29.44,28.89,22.22,28.33
2022-12-29 00:00:00,25.0,24.44,25.56,32.22,25.0,25.56,26.11,25.56,26.67,27.22,...,24.44,23.33,22.78,24.44,23.89,27.22,27.22,28.33,22.22,27.22
2022-12-30 00:00:00,25.0,24.44,25.56,32.22,23.89,24.44,25.56,25.56,25.56,26.11,...,26.11,22.78,23.33,22.22,24.44,26.67,28.89,28.89,22.22,28.33
2022-12-31 00:00:00,24.44,23.33,25.0,32.22,23.33,24.44,24.44,24.44,26.67,24.44,...,26.67,24.44,24.44,25.56,27.22,27.22,28.89,27.78,22.22,28.33

In [8]:
df_main.shape 

#there are 365 days in a year. We have data from 1980 to 2022 (42 years). 42 X 365 = 15,000~

(15706, 72)

In [ ]:
Facebook prophet - Fatimah
SARIMAX - Aliyu
ARMA - 
ARIMA - Marufdeen
SARIMA - Yusuf

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 15711 entries, STATION to 2022-12-31 00:00:00
dtypes: float64(15709), object(2)
memory usage: 8.6+ MB